### ISSUE TITLE
Question about sync_timeout

### ISSUE THREAD

**Issue by liangxin1300** [corosync/corosync-qdevice#21] opened 2021-04-09 07:39 UTC
Hi @jfriesse,

I have a question: 

What is `sync_timeout` and the `sync phase`? which mentioned in `man corosync-qdevice`

Maybe I overlooked something, but I cannot find this value `sync_heartbeat_interval` been actually used at some timer functions in source code

Thanks!

**Comment by jfriesse** [comment] 2021-04-09 09:03
Hi @liangxin1300 
yes, you are right. `sync_timeout` is really never used directly.

Original idea was to use it during `sync phase` what is corosync phase of new membership installation. Default action is not continue to final membership installation phases until all services are synced and it is used for votequorum to wait until `votequroum_qdevice_poll` is called (check votequorum.c - `votequorum_sync_init` which is installing timer and `votequorum_sync_process` which returns error code until timeout or `votequroum_qdevice_poll` is called). 

At the end I've found out that there is not really any moment when this timeout can be used because qdevice either has info from qnetd (so it can poll normally) or doesn't have that info and then it cannot vote (neither ACK nor NACK).

It is however used for heuristics.sync_timeout (see https://github.com/corosync/corosync-qdevice/blob/e1d5914069bc50c954aa8780fac5c2f3b04869e2/qdevices/qdevice-instance.c#L110) and in theory can be used for some other (not yet existing) model (probably not heuristics one, but disk one).

No matter what, description in man page is not ideal but it is also not incorrect (qdevice should really call votequorum_qdevice_poll every 30 sec during sync phase, but it is not doing it deliberately).

Please don't hesitate to ask more questions if you have some.

**Comment by liangxin1300** [comment] 2021-04-09 09:45
Thanks @jfriesse !

I'm wondering how to trigger `qdevice_timer_fn` be called? 
I cannot see this line printed in log `log_printf(LOGSYS_LEVEL_INFO, "lost contact with quorum device %s", qdevice_name);` after killing corosync-qdevice process

**Comment by jfriesse** [comment] 2021-04-09 12:34
@liangxin1300 It's usually not very easy to trigger it. Easiest way is to follow https://github.com/corosync/corosync-qdevice/issues/10 with old qdevice/qnetd or you can try to comment out `votequroum_qdevice_poll` in qdevice

**Comment by gao-yan** [comment] 2021-04-09 12:51
Thanks for the information @jfriesse!

This makes me wonder if it makes sense for sbd to check qdevice's sync_timeout against watchdog timeout here:
https://github.com/ClusterLabs/sbd/pull/114

@wenningerk Is it necessary have this limitation?

**Comment by wenningerk** [comment] 2021-04-09 13:09
I remember we actually a split-brain observed due to it.
But I also remember that @jfriesse fixed/changed something afterwards.
So that situation might not occur anymore.
But corosync-timing in combination with sbd is a delicate thing anyway as sbd somehow breaks the virtual-synchrony approach and as time it takes to actually form a membership isn't defined when it takes multiple cycles.
In the end the critical situation is when quorum-state-update is delayed for a significantly different time (difference > watchdog-timeout more or less) in the partitions of a cluster.

**Comment by gao-yan** [comment] 2021-04-12 15:18
> I remember we actually observed a split-brain due to it.
> But I also remember that @jfriesse fixed/changed something afterwards.

Do you probably mean this https://github.com/corosync/corosync-qdevice/commit/11a861c93fe4b0594afb60a3993d5ba9f443fba5 ?

> So that situation might not occur anymore.
> But corosync-timing in combination with sbd is a delicate thing anyway as sbd somehow breaks the virtual-synchrony approach and as maximum time it takes to actually form a membership isn't defined when it takes multiple cycles.
> In the end the critical situation is when quorum-state-update is delayed for a significantly different time (difference > watchdog-timeout more or less) in the partitions of a cluster.
> So trying to find a solution for that is one of my current projects.

Makes sense. But still, currently sbd seems to check against a wrong timeout sync_timeout,  which is neither directly used by qdevice nor recommended to be changed according to man page, hence prevent itself from starting.

**Comment by wenningerk** [comment] 2021-04-13 08:23
> Makes sense. But still, currently sbd seems to check against a wrong timeout sync_timeout, which is neither directly used by qdevice nor recommended to be changed according to man page, hence prevent itself from starting.

Guess I have to have a deeper look into that ... give me a bit ...

**Comment by jfriesse** [comment] 2021-04-13 08:29
I believe original question/issue is now clear so closing this issue.

But don't hesitate to continue discussing the sbd timeouts if you like to.

**Closed by jfriesse** 2021-04-13 08:29 UTC

**Comment by wenningerk** [comment] 2021-04-13 08:56
@jfriesse do I get it correctly that sync_timeout is still basically the time sync-phase can be extended to in a cluster-partition in principle - due to use of qdevice? If the 30s are not what would be effective in the case of qnet, could we make it provide a value that is more reasonable? Idea is that instances like sbd who want to e.g. know how long quorum-update could be delayed (with a reasonable probability - I know it is indefinite in principle and that sbd is still missing a mechanism to pull the trigger if that high-probability assumption is exceeded) have a possible source to get that information. (In case of sbd what we really are interested is rather the asymmetry in delay that is possible between partitions of course - but that is maybe another story ...)

**Comment by jfriesse** [comment] 2021-04-13 09:05
@wenningerk sync_timeout hasn't changed so probably it is as you saying. So default 30 sec is "maximum" what corosync spends in sync phase before forming membership and inform API clients.

**Comment by wenningerk** [comment] 2021-04-13 09:12
So as a consequence - how unpleasant it might be for certain cases with maybe potential to improve there with some extra info - what sbd is assuming atm is correct :-(

**Comment by gao-yan** [comment] 2021-05-14 15:29
It seems about: https://bugzilla.redhat.com/show_bug.cgi?id=1703128

It's not clear though from which revision of qdevice or with what specific versions of qdevice, update of quorum is no longer guaranteed to be timely.

If so, isn't it a regression of qdevice which should be fixed?

**Comment by wenningerk** [comment] 2021-05-14 15:41
As I got it that is by design and has always been there with qdevice.

**Comment by gao-yan** [comment] 2021-05-14 15:59
Which version of corosync-qdevice did you produce the behavior with as described in the rhbz#1703128? It doesn't produce for me at least with the qdevice from corosync-2.4.5.

**Comment by jfriesse** [comment] 2021-05-17 06:59
@gao-yan: The problem of suboptimal timeouts is fully fixed in qdevice 3.0.1 and it is also fixed in not yet released corosync 2.4 (needle) in git.

Also problem is not that easy to reproduce with default settings. It's quite reliably reproducible for 2 node cluster with default (1sec) token timeout. But it's becoming hard to reproduce (or impossible to reproduce) for cluster with more than 2 nodes or higher token timeout.

**Comment by gao-yan** [comment] 2021-05-17 12:25
Thanks for the information, @jfriesse.

Now with 1s token timeout, it seems to always produce even with the latest needle revision https://github.com/corosync/corosync/commit/6236728a6136e3e2ceef2709cda51196b89bc689 .

On the first node:
```
opensuse151-1:~ # killall -STOP corosync-qdevice; ./block-opensuse151-2.sh; date
Mon May 17 13:51:03 CEST 2021
```
```
May 17 13:51:04 opensuse151-1 corosync[11909]:   [TOTEM ] A processor failed, forming new configuration.
May 17 13:51:05 opensuse151-1 corosync[11909]:   [VOTEQ ] waiting for quorum device Qdevice poll (but maximum for 30000 ms)
May 17 13:51:05 opensuse151-1 corosync[11909]:   [TOTEM ] A new membership (192.168.122.101:4294971150) was formed. Members left: 1084783206
May 17 13:51:05 opensuse151-1 corosync[11909]:   [TOTEM ] Failed to receive the leave message. failed: 1084783206
May 17 13:51:35 opensuse151-1 corosync[11909]:   [VOTEQ ] lost contact with quorum device Qdevice
May 17 13:51:35 opensuse151-1 corosync[11909]:   [QUORUM] This node is within the non-primary component and will NOT provide any services.
May 17 13:51:35 opensuse151-1 corosync[11909]:   [QUORUM] Members[1]: 1084783205
May 17 13:51:35 opensuse151-1 corosync[11909]:   [MAIN  ] Completed service synchronization, ready to provide service.
```

On the other node:
```
May 17 13:51:04 opensuse151-2 corosync[11249]:   [TOTEM ] A processor failed, forming new configuration.
May 17 13:51:05 opensuse151-2 corosync[11249]:   [VOTEQ ] waiting for quorum device Qdevice poll (but maximum for 30000 ms)
May 17 13:51:05 opensuse151-2 corosync[11249]:   [TOTEM ] A new membership (192.168.122.102:4294971150) was formed. Members left: 1084783205
May 17 13:51:05 opensuse151-2 corosync[11249]:   [TOTEM ] Failed to receive the leave message. failed: 1084783205
May 17 13:51:08 opensuse151-2 corosync[11249]:   [QUORUM] Members[1]: 1084783206
May 17 13:51:08 opensuse151-2 corosync[11249]:   [MAIN  ] Completed service synchronization, ready to provide service.
```

Has there been any fixes that are supposed to help with this situation?

If there are always potential situations where it might take sync_timeout to get quorum state updated, would it make sense to recommend to configure a shorter sync_timeout to ensure update of quorum is more timely?

**Comment by jfriesse** [comment] 2021-05-17 12:50
@gao-yan The qnetd part is important, so please make sure to update qnetd.

**Comment by gao-yan** [comment] 2021-05-17 13:12
@jfriesse Qnetd is the same revision.

**Comment by jfriesse** [comment] 2021-05-17 13:25
@gao-yan Weird. Are you sure cfa2502db27115abe622438ca26a4d7f9b6e4dbb is really included and qnetd was restarted (and default options are used)?

**Comment by gao-yan** [comment] 2021-05-17 14:02
Double-checked it, the qnetd server and both the cluster nodes are running corosync-2.4.5.69-6236 which was created with `make dist` and includes https://github.com/corosync/corosync/commit/cfa2502db27115abe622438ca26a4d7f9b6e4dbb

Settings on qdevice sides are normal:

```
totem {
        token:          1000
...
        transport: udpu
}

nodelist {
        node {
                ring0_addr: 192.168.122.101
        }
        node {
                ring0_addr: 192.168.122.102
        }
}

quorum {
         device {
           votes: 1
           model: net
           net {
             tls: off
             host: 192.168.122.103
             algorithm: ffsplit
             tie_breaker: highest
           }
}
```

Qnetd side, the only non-default setting is TLS being off in corosync-qnetd sysconfig:
```
COROSYNC_QNETD_OPTIONS="-s off"
```

**Comment by jfriesse** [comment] 2021-05-17 14:27
@gao-yan Weird. Can you run qnetd with debugging and see how long it takes before qnetd reacts to "-STOP" of qdevice? It should be 12-13 sec

**Comment by gao-yan** [comment] 2021-05-17 14:44
```
opensuse151-1:~ # killall -STOP corosync-qdevice; ./block-opensuse151-2.sh; date
Mon May 17 16:36:47 CEST 2021
```

The qnetd server seemed to have reacted relatively soon:
```
May 17 16:36:49 opensuse151-3 corosync-qnetd[24769]: Client ::ffff:192.168.122.102:34734 (cluster opensuse151, node_id 1084783206) sent membership node list.
May 17 16:36:49 opensuse151-3 corosync-qnetd[24769]:   msg seq num = 6
May 17 16:36:49 opensuse151-3 corosync-qnetd[24769]:   ring id = (40a87a66.10000100a)
May 17 16:36:49 opensuse151-3 corosync-qnetd[24769]:   heuristics = Undefined
May 17 16:36:49 opensuse151-3 corosync-qnetd[24769]:   Node list:
May 17 16:36:49 opensuse151-3 corosync-qnetd[24769]:     0 node_id = 1084783206, data_center_id = 0, node_state = not set
May 17 16:36:49 opensuse151-3 corosync-qnetd[24769]: ffsplit: Membership for cluster opensuse151 is not yet stable
May 17 16:36:49 opensuse151-3 corosync-qnetd[24769]: Algorithm result vote is Wait for reply
May 17 16:36:57 opensuse151-3 corosync-qnetd[24769]: Client ::ffff:192.168.122.101:55488 doesn't sent any message during 10000ms. Disconnecting
May 17 16:36:57 opensuse151-3 corosync-qnetd[24769]: Client ::ffff:192.168.122.101:55488 (init_received 1, cluster opensuse151, node_id 1084783205) disconnect
May 17 16:36:57 opensuse151-3 corosync-qnetd[24769]: ffsplit: Membership for cluster opensuse151 is now stable
May 17 16:36:57 opensuse151-3 corosync-qnetd[24769]: ffsplit: Quorate partition selected
May 17 16:36:57 opensuse151-3 corosync-qnetd[24769]:   Node list:
May 17 16:36:57 opensuse151-3 corosync-qnetd[24769]:     0 node_id = 1084783206, data_center_id = 0, node_state = not set
May 17 16:36:57 opensuse151-3 corosync-qnetd[24769]: ffsplit: No client gets NACK
May 17 16:36:57 opensuse151-3 corosync-qnetd[24769]: Sending vote info to client ::ffff:192.168.122.102:34734 (cluster opensuse151, node_id 1084783206)
May 17 16:36:57 opensuse151-3 corosync-qnetd[24769]:   msg seq num = 2
May 17 16:36:57 opensuse151-3 corosync-qnetd[24769]:   vote = ACK
May 17 16:36:57 opensuse151-3 corosync-qnetd[24769]: Client ::ffff:192.168.122.102:34734 (cluster opensuse151, node_id 1084783206) replied back to vote info message
May 17 16:36:57 opensuse151-3 corosync-qnetd[24769]:   msg seq num = 2
May 17 16:36:57 opensuse151-3 corosync-qnetd[24769]: ffsplit: All ACK votes sent for cluster opensuse151
May 17 16:36:57 opensuse151-3 corosync-qnetd[24769]: Client ::ffff:192.168.122.102:34734 (cluster opensuse151, node_id 1084783206) sent quorum node list.
May 17 16:36:57 opensuse151-3 corosync-qnetd[24769]:   msg seq num = 7
May 17 16:36:57 opensuse151-3 corosync-qnetd[24769]:   quorate = 1
May 17 16:36:57 opensuse151-3 corosync-qnetd[24769]:   Node list:
May 17 16:36:57 opensuse151-3 corosync-qnetd[24769]:     0 node_id = 1084783205, data_center_id = 0, node_state = dead
May 17 16:36:57 opensuse151-3 corosync-qnetd[24769]:     1 node_id = 1084783206, data_center_id = 0, node_state = member
May 17 16:36:57 opensuse151-3 corosync-qnetd[24769]: Algorithm result vote is No change
```

But the node declared loss of qdevice much later than that:
```
May 17 16:36:48 opensuse151-1 corosync[7013]:   [TOTEM ] A processor failed, forming new configuration.
May 17 16:36:49 opensuse151-1 corosync[7013]:   [VOTEQ ] waiting for quorum device Qdevice poll (but maximum for 30000 ms)
May 17 16:36:49 opensuse151-1 corosync[7013]:   [TOTEM ] A new membership (192.168.122.101:4294971402) was formed. Members left: 1084783206
May 17 16:36:49 opensuse151-1 corosync[7013]:   [TOTEM ] Failed to receive the leave message. failed: 1084783206
May 17 16:37:19 opensuse151-1 corosync[7013]:   [VOTEQ ] lost contact with quorum device Qdevice
May 17 16:37:19 opensuse151-1 corosync[7013]:   [QUORUM] This node is within the non-primary component and will NOT provide any services.
May 17 16:37:19 opensuse151-1 corosync[7013]:   [QUORUM] Members[1]: 1084783205
May 17 16:37:19 opensuse151-1 corosync[7013]:   [MAIN  ] Completed service synchronization, ready to provide service.
```

**Comment by jfriesse** [comment] 2021-05-17 14:50
@ gao-yan And that loss is happening on node where -STOP was sent or the other node? Because the main problem was non-responsiveness on other node. It is expected that when process is paused corosync declares that quorum device connection was lost. That's not what is the issue about.

**Comment by gao-yan** [comment] 2021-05-17 15:16
The loss happened on the node where -STOP was sent. It's just that it happened very late. The other node kept the vote from qdevice though.

Well, it's still an issue at least from disk-less sbd's point of view though. For a period time, after the node with the paused qdevice has been declared being lost by the other node, it's still technically holding the existing “vote” until sync_timeout is popped. So when the other node considers this node has lost the quorum, it actually hasn't happened yet ...

If this situation is unavoidable, indeed disk-less sbd still has to have a watchdog timeout longer than qdevice sync_timeout.

**Comment by gao-yan** [comment] 2021-05-17 15:39
> If this situation is unavoidable, indeed diskless sbd still has to have a watchdog timeout longer than qdevice sync_timeout.

And if so, would you recommend to configure a shorter sync_timeout to ensure update of quorum on the node with paused qdevice is more timely?

**Comment by jfriesse** [comment] 2021-05-18 06:25
@gao-yan: The reason why sync_timeout exists is to give qdevice time to finish heuristics (which can take long time). Of course it is possible to use shorter sync_timeout, but I wouldn't say I recommend it. Ideal solution would be to use power fencing (where possible) which solves this "problem". I really don't have any idea of solution for sbd. There were some ideas to inform sbd about membership change before sync phase (so sbd knows something is happening) - I was thinking again about it and even it wouldn't solve problem completely (because when heuristics would take long time sbd may fence the node just because heuristics took too long, so good for sbd, bad for qdevice heuristics) it would help.

**Comment by gao-yan** [comment] 2021-05-18 11:16
@jfriesse Thanks for the clarification and information!

**Comment by jfriesse** [comment] 2021-05-18 17:02
@gao-yan Yup, no problem. I was also thinking a bit more about the problem and I think we may end up with some extra functionality just for sbd because it looks like it really needs to know some internals which are not really good fit for generic public API.
